version: 2
updates:
  # Configuration for npm dependencies
  - package-ecosystem: "npm" # Use "pip" for Python, "maven" for Java, etc.
    directory: "/" # Location of the package manifests
    schedule:
      interval: "weekly" # Options: daily, weekly, monthly
    open-pull-requests-limit: 10
    reviewers:
      - "your-github-username" # Add reviewer(s) for PRs
    assignees:
      - "your-github-username"
    labels:
      - "dependencies"
      - "bot"
    ignore:
      - dependency-name: "some-package"
        versions: [">=2.0.0"]
  
  # Configuration for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/" # Root directory for GitHub Actions workflows
    schedule:
      interval: "weekly"

  # Configuration for Docker dependencies
  - package-ecosystem: "docker"
    directory: "/" # Root directory containing Dockerfiles
    schedule:
      interval: "monthly"
